### PR TITLE
Add support for django 1.10

### PR DESCRIPTION
**Pull request by nautilebleu**

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
Hmm, why CI build was failed?

**Comment by nautilebleu** [comment]
It's seems my latest changes are not compatible with Python2.7. I look to find why.

**Comment by nautilebleu** [comment]
Ok I understand why: the build is run against django 1.3.1. There's a lots of change in django since so maintain compat with this really old version won't be easy.

**Comment by joshowen** [comment]
Django 1.3.1 hasn't been supported in years, can it be removed from the test matrix?

**Comment by svetlyak40wt** [comment]
I think, we can drop support for Django < 1.8.

**Comment by svetlyak40wt** [comment]
Actually, there is no test matrix in this project. I think tox configuration from github.com/ionelmc/cookiecutter-pylibrary could be take and adopted for this library.

@nautilebleu do you want to add a tox and test matrix support in this pull?

**Comment by nautilebleu** [comment]
I've never done this before, I'll try next week!

**Comment by svetlyak40wt** [comment]
Good try @nautilebleu but try to generate a project skeleton from https://github.com/ionelmc/cookiecutter-pylibrary and see how it is configured inside. For example, run:
```
pip install cookiecutter
cookiecutter https://github.com/ionelmc/cookiecutter-pylibrary
# answer to the wizard's questions
# then investigate tox.ini and .travis.yml files inside the generated project
```

**Comment by nautilebleu** [comment]
I've follow this blogpost http://joebergantine.com/blog/2015/dec/03/test-reusable-django-application-support-multiple-/ which seems more accurate as it explains how to use tox and travis with a django reusable app.

This leads to this kind of output
https://travis-ci.org/nautilebleu/django-fields/jobs/154087384

which is "OK" as the only remaining error is not related to tox/travis but is a test that fails anyway. I don't know how to fix the error, caused by changes in django Model _meta. If someone has an idea, let me know!

I've also removed the files that seem unecessary since the refactor. Previously the way for running the tests from the CLI and from travis was using the ``run-tests.sh`` file. Now for travis, we use tox. Is it ok to also use tox from CLI?

**Comment by joshowen** [comment]
Is anyone still working on this?  If not I can take a look.

**Comment by nautilebleu** [comment]
Hi,

If you can manage to fix the remaining test that fails, don't hesitate! :)

**Comment by blockjon** [comment]
+1 for getting this working... I will use the completed work as soon as you release it!

**Comment by joshowen** [comment]
@nautilebleu Thoughts on just removing `ModelWithPrivateFields`?  It looks like it hasn't worked in any modern Django version.

**Comment by nautilebleu** [comment]
@joshowen Ok for me but I'm not one of the maintainers! :)

**Comment by joshowen** [comment]
@svetlyak40wt thoughts?

**Comment by svetlyak40wt** [comment]
Guys, I really have not time for maintenance of this library anymore. But I'll be glad of somebody will take over this process.

**Comment by joshowen** [comment]
@svetlyak40wt Perhaps we can move the project to https://github.com/jazzband.  I'm happy to help with that if you're interested in moving in that direction.

**Comment by svetlyak40wt** [comment]
I'll investigate how Jazzband works. Thanks!

**Comment by joshowen** [comment]
hey @svetlyak40wt let me know if i can help out at all.  Thanks!

**Pull request merged**
